require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/smokers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Smoker. As you add validations to Smoker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Smoker.create! valid_attributes
      get smokers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      smoker = Smoker.create! valid_attributes
      get smoker_url(smoker)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_smoker_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      smoker = Smoker.create! valid_attributes
      get edit_smoker_url(smoker)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Smoker" do
        expect {
          post smokers_url, params: { smoker: valid_attributes }
        }.to change(Smoker, :count).by(1)
      end

      it "redirects to the created smoker" do
        post smokers_url, params: { smoker: valid_attributes }
        expect(response).to redirect_to(smoker_url(Smoker.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Smoker" do
        expect {
          post smokers_url, params: { smoker: invalid_attributes }
        }.to change(Smoker, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post smokers_url, params: { smoker: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested smoker" do
        smoker = Smoker.create! valid_attributes
        patch smoker_url(smoker), params: { smoker: new_attributes }
        smoker.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the smoker" do
        smoker = Smoker.create! valid_attributes
        patch smoker_url(smoker), params: { smoker: new_attributes }
        smoker.reload
        expect(response).to redirect_to(smoker_url(smoker))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        smoker = Smoker.create! valid_attributes
        patch smoker_url(smoker), params: { smoker: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested smoker" do
      smoker = Smoker.create! valid_attributes
      expect {
        delete smoker_url(smoker)
      }.to change(Smoker, :count).by(-1)
    end

    it "redirects to the smokers list" do
      smoker = Smoker.create! valid_attributes
      delete smoker_url(smoker)
      expect(response).to redirect_to(smokers_url)
    end
  end
end
